name: yo_te_pago
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^2.6.1
  go_router: ^15.0.0
  http: ^1.4.0
  intl: ^0.20.2
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  path_provider: ^2.1.5
  sqflite: ^2.4.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  isar_generator: ^3.0.5

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/icons/

  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"